# Generated by Django 5.0.6 on 2024-10-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_homepage_link_profile_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
